#pragma once

enum {
    RTL_SDR_SOURCE_IFACE_CMD_GET_GAIN_COUNT,
    RTL_SDR_SOURCE_IFACE_CMD_GET_GAIN_ID,
    RTL_SDR_SOURCE_IFACE_CMD_SET_GAIN_ID,
    RTL_SDR_SOURCE_IFACE_CMD_GET_DB_TEXT,

    RTL_SDR_SOURCE_IFACE_CMD_IS_RUNNING,
	RTL_SDR_SOURCE_IFACE_CMD_IS_RTL_AGC,
	RTL_SDR_SOURCE_IFACE_CMD_IS_TUNER_AGC,
	RTL_SDR_SOURCE_IFACE_CMD_IS_BIAS_T,
	
	RTL_SDR_SOURCE_IFACE_CMD_TOGGLE_RTL_AGC,
	RTL_SDR_SOURCE_IFACE_CMD_TOGGLE_TUNER_AGC,
	RTL_SDR_SOURCE_IFACE_CMD_TOGGLE_BIAS_T,
	
    RTL_SDR_SOURCE_IFACE_CMD_GET_SAMPLE_RATE_INDEX,
    RTL_SDR_SOURCE_IFACE_CMD_SET_SAMPLE_RATE_INDEX,
	
	RTL_SDR_SOURCE_IFACE_CMD_GET_DEVICE_COUNT,
	RTL_SDR_SOURCE_IFACE_CMD_REFRESH
};
